# based on:
# https://www.getzola.org/documentation/deployment/netlify/

[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.14.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200


[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
